language: objective-c

osx_image: xcode7.1

before_install:
  - gem install cocoapods -v '0.39.0'

xcode_workspace: Classmere.xcworkspace
xcode_scheme: Classmere

script:
  - xctool -workspace Classmere.xcworkspace -scheme Classmere -sdk iphonesimulator build test
